---
title: "R Notebook"
output: html_notebook
---

Aritmetica en R
```{r}
3+5     #suma
5-1     #resta    
5*2     #multiplicaci贸n
(5-2)/2 #divisi贸n
2^5     #potencia
28%%6   #m贸dulo
```

Variables
se asigna el tipo al momento de asignar el valor
```{r}
x<-10
x
```
Asignaci贸n de variables
```{r}
x<-10
y<-15
total=x+y
total
```
tipos de datos
```{r}
my_character<-"universe"
my_logical<-FALSE

my_character
my_logical
```

```{r}
class(my_character)
class(my_logical)
```

```{r}
numeric_vector<-c(1,10,49)
character_vector<-c("a","b","c")
boolean_vector<-c(FALSE,TRUE,TRUE)

numeric_vector
character_vector
boolean_vector
```

```{r}
poker_vector<-c(140,-50,20,-120,240)
roulette_vector<-c(-24,-50,100,-350,10)

names(poker_vector)<-c("Monday","Tuesday","Wednesday","Thursday","Friday")
names(roulette_vector)<-c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector
roulette_vector
```
Comparando y seleccionando
```{r}
age<-17
age>=18

a_vector<-c(1,2,3)
b_vector<-c(4,5,6)

total_vector <-a_vector+b_vector
total_vector

total_daily <- poker_vector+roulette_vector
total_daily

total_poker<-sum(poker_vector)
total_roulette<-sum(roulette_vector)

total_sum<-sum(total_poker,total_roulette)
total_sum

poker_vector
poker_vector[3]
poker_vector[c(1,3,4)]
roulette_vector[2:5]

poker_start<-poker_vector[c("Monday","Wednesday","Thursday")]
mean(poker_start)

selection_vector<-poker_vector>0
selection_vector

poker_Winning_days<-poker_vector[selection_vector]
poker_Winning_days
```

Matrices
```{r}
new_hope<-c(460.998, 314.4)
empire_strike<-c(2980.475, 247.9 )
return_jedi<-c(309.306, 165.8)

box_office<-c(new_hope, empire_strike, return_jedi)
box_office

stars_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)
stars_wars_matrix

region <- c("US", "non-US")
titles <- c("A new Hope", "The Empire Strikes Back", "Return of the Jedi")

colnames(stars_wars_matrix) <- region
rownames(stars_wars_matrix) <- titles

stars_wars_matrix
```
rowsums
```{r}
worldwide_vector <- rowSums(stars_wars_matrix)
worldwide_vector

all_wars_variable <- cbind(stars_wars_matrix, worldwide_vector)
all_wars_variable

worldwide_cols <- colSums(all_wars_variable)
worldwide_cols

all_wars_variable <- rbind(all_wars_variable, worldwide_cols)
all_wars_variable

```

Selection of matrix elements
```{r}
non_us_all <- all_wars_variable[1:3,2]
non_us_all

mean(non_us_all)

```

Aritmetica con matrices
```{r}
us_all <- all_wars_variable[1:3,1]
us_all <- us_all * 0.12
us_all

```

factores
```{r}
sex_vector<-c("Male","Female","Female","Male","Male")

factor_sex_vector<-factor(sex_vector)
factor_sex_vector

temperature_vector<-c("High","Low","High","Low", "Medium")
factor_temperature_vector<-factor(temperature_vector,ordered = TRUE, levels = c("Low","Medium","High") )

factor_temperature_vector
```

Factor levels
```{r}

survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector)

factor_survey_vector

levels(factor_survey_vector) <- c("Female","Male")
factor_survey_vector

```

Summarizing a factor
```{r}
summary(survey_vector)
summary(factor_survey_vector)

male <- factor_survey_vector[1]
male

female <- factor_survey_vector[2]
female

male > female


speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels=c("slow","medium","fast"))
factor_speed_vector

da2 <- factor_speed_vector[2]
da3 <- factor_speed_vector[1]

da2
da3

da2 > da3

```
